### ISSUE TITLE
Publishing on pypi?

### ISSUE THREAD

**Issue by simonsmiley** [tBaxter/vobject#10]
It would be nice to have this published on pypi.
I don't really care about the name. Other projects can't move to python3 because of vobject not supporting it.
https://github.com/aldryn/aldryn-people/issues/28

**Comment by tBaxter** [comment]
There was someone interested in taking over the project (http://lists.skyhouseconsulting.com/pipermail/vobject/2015-April/subject.html). They were going to pull in my changes, host it on SourceForge, update it in Pypi and all of that. I'm not sure what happened with any of that, though.

I'd be happy to let someone else take it, but other than that effort above, I haven't seen much movement, and I haven't seen much from that one lately.

In the meantime, you *could* pip install from Git.

I *could* be persuaded to put it on pypi myself, but I"m just not really sure I'm the best long-term maintainer of this. And I'd probably need a new name :-)

**Comment by dokterbob** [comment]
Hey @tBaxter, please let me try and persuade you to indeed publish your work on PyPI. If needed, under a different name.

Maintained or not, as long as you are not standing in the way of further development (by being willing to transfer ownership to more active developers, if asked) I think having it on PyPI would be a *very* welcomed contribution. Being the maintainer of a Python package ([django-newsletter](https://github.com/dokterbob/django-newsletter/issues/102#issuecomment-168297664))with `vobject` as a reference, I would much prefer to have my package not to have any dependencies installed straight from GitHub. 

This way, I can require a particular major version rather than a specific commit to be installed, reducing chances of conflicts, and it would make the installation so much more efficient.

Alternately, I might have to consider including your vobject branch directly into my code, which is even less elegant.

Many thanks in advance!

**Comment by simonsmiley** [comment]
I guess I could maintain it. I don't really know anything about the code, but I'm good enough in python to be able to fix stuff and write tests. I guess that's most of what's needed anyway.
We could create an organization and have a repo there. I guess we could also ask skyhouseconsulting.com if they would release the name for us to pick up. otherwise we would have to come up with a new name

**Comment by dokterbob** [comment]
Seems like a fine plan. I could help reviewing PR's every now and then. 

Simon Hanna <notifications@github.com> schreef op 3 januari 2016 23:14:55 CET:

**Comment by tBaxter** [comment]
@dokterbob Suggestions on a new name?

**Comment by dokterbob** [comment]
vobject-new-name? ;)

**Comment by simonsmiley** [comment]
I guess vobject3 would be the best. It's still the old one but says everything about python3 support

**Comment by dokterbob** [comment]
Sounds like a much better suggestion. :)

**Comment by tBaxter** [comment]
Take a look at https://pypi.python.org/pypi/python-card-me and let me know how it's working for you.

**Comment by simonsmiley** [comment]
looks good, will you create a new repo?

**Comment by dokterbob** [comment]
@tBaxter Seems like a good suggestion, or are there any reasons not to use it?

**Comment by tBaxter** [comment]
None that I see. It's passing tests and is the same thing as my vobject fork here, with a few minor updates and changes. Nothing significant. So, I'm going to shift my efforts to that project. 

@simonsmiley the repo is already created: https://github.com/tBaxter/python-card-me
